spring.application.name=serana

spring.datasource.url = jdbc:postgresql://localhost:5432/db_serana
spring.datasource.username=User-PG
spring.datasource.password=Grupo-03-2024

spring.jpa.show-sql = false
spring.jpa.hibernate.ddl-auto = create-drop
